import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import AuthGuard from "@/components/auth/AuthGuard";
import "./globals.css";

const ibmSans = IBM_Plex_Sans_Thai({
  variable: "--font-ibm",
  subsets: ["latin", "thai"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmSans.variable} ${ibmSans.className}  antialiased`}>
        <AuthGuard>{children}</AuthGuard>
      </body>
    </html>
  );
}
